basePath: /api/v1
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.GeneratePostRequest:
    properties:
      note_id:
        type: integer
    required:
    - note_id
    type: object
  dto.PostListResponse:
    properties:
      page:
        type: integer
      posts:
        items:
          $ref: '#/definitions/dto.PostResponse'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  dto.PostResponse:
    properties:
      content_md:
        type: string
      created_at:
        type: string
      id:
        type: integer
      note_id:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8082
info:
  contact: {}
  description: Сервис оркестрации для платформы VOY
  title: VOY API - Orchestrator Service
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Получает список постов текущего пользователя
      parameters:
      - description: Номер страницы
        in: query
        name: page
        type: integer
      - description: Размер страницы
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostListResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить список постов
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет пост по ID
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить пост
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: Получает пост по ID
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить пост
      tags:
      - posts
  /posts/generate:
    post:
      consumes:
      - application/json
      description: Генерирует новый пост на основе заметки
      parameters:
      - description: Данные для генерации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GeneratePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.PostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Сгенерировать пост
      tags:
      - posts
securityDefinitions:
  BearerAuth:
    description: Введите токен в формате "Bearer {token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
