basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is an API service for generating AI content using Ollama models.
  title: AI Content Generator API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
